apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging-website
  labels:
    app.kubernetes.io/name: website-frontend
    app.kubernetes.io/instance: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: website-frontend
      app.kubernetes.io/instance: staging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: website-frontend
        app.kubernetes.io/instance: staging
    spec:
      containers:
        - image: registry.robocup.de/website/frontend:2.7.1-sha-377fcbec06331c32200264da6b5be615aac2da1b
          name: website-frontend
          env:
            - name: NUXT_RELEASE_VERSION
              value: "2.7.1"
            - name: NUXT_RELEASE_SHA
              value: "377fcbec06331c32200264da6b5be615aac2da1b"
          envFrom:
            - configMapRef:
                name: website-frontend-config
            - secretRef:
                name: website-frontend
                optional: false
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            failureThreshold: 3
            periodSeconds: 20
      imagePullSecrets:
        - name: registry
